Tokenizer to v10.2.7, resolve conflict with transformers
ERROR: Cannot install gramformer and gramformer==1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    gramformer 1.0 depends on tokenizers==0.10.2
    transformers 2.11.0 depends on tokenizers==0.7.0